name: 'Setup Go with Private Repository Access'
description: 'Sets up Go and configures GitHub CLI authentication for private repositories inside this org (konfidence-project)'

runs:
  using: 'composite' 
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.go-version-file }}
    
 