name: 'Vendir Sync'
description: 'Syncs vendir dependencies'
inputs:
  vendir-config-file:
    description: 'Path to vendir config file'
    required: true
    default: 'vendir.yml'

runs:
  using: 'composite' 
  steps:
    - name: Install vendir
      shell: bash
      run: |
        wget -O- https://carvel.dev/install.sh > install.sh
        chmod +x install.sh
        ./install.sh
    - name: Sync vendir dependencies
      shell: bash
      run: |
        make vendir-sync
    - name: Print vendir sync output
      shell: bash
      run: |
        tree