name: Kubebuilder Tests


jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/konfidence-project
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: 1702387
          private-key: ${{ secrets.KONFIDENCE_PROJECT_REPO_ACCESS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Setup Go with private repos
        uses: ./.github/actions/setup-go
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Running Tests
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          go mod tidy
          make test 