name: Semantic Release
description: Complete semantic release setup and execution with automatic config detection
author: konfidence-project

inputs:
  dry-run:
    description: Whether to run semantic release in dry-run mode
    required: false
    default: "false"
outputs:
  new-release-published:
    description: Whether a new release was published
    value: ${{ steps.release.outputs.new_release_published }}
  new-release-version:
    description: Version of the new release
    value: ${{ steps.release.outputs.new_release_version }}

runs:
  using: composite
  steps:

    - name: Clone semantic-release config
      uses: actions/checkout@v4
      with:
        repository: konfidence-project/.github
        path: semantic-release
        sparse-checkout: semantic-release/.releaserc.json
        token: ${{ env.GITHUB_TOKEN }}

    - name: Copy semantic-release config
      shell: bash
      run: |
        cp semantic-release/semantic-release/.releaserc.json .releaserc.json

    - name: Execute semantic release
      id: release
      uses: cycjimmy/semantic-release-action@v4
      with:
        dry_run: ${{ inputs.dry-run }}
        extra_plugins: |
            @semantic-release/commit-analyzer 
            @semantic-release/release-notes-generator 
            @semantic-release/github 
            @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
