name: Go Module Build and Release

on: 
  workflow_call:
    outputs:
      version:
        description: 'Version that was created'
        value: ${{ jobs.release.outputs.version }}
      new-release-published:
        description: 'Whether a new release was published'
        value: ${{ jobs.release.outputs.new-release-published }}

jobs: 
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    outputs:
      version: ${{ steps.semantic-release.outputs.new-release-version }}
      new-release-published: ${{ steps.semantic-release.outputs.new-release-published }}
    steps:
      - name: Setup GitHub Repo Access
        uses: konfidence-project/.github/.github/actions/github-repo-access@v3
        with:
          private-key: ${{ secrets.KONFIDENCE_PROJECT_REPO_ACCESS_PRIVATE_KEY }}

      - name: Clone the code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ env.GH_TOKEN }}

      - name: Set GOPRIVATE
        run: echo "GOPRIVATE=github.com/konfidence-project" >> $GITHUB_ENV

      - name: Semantic Release
        id: semantic-release
        uses: konfidence-project/.github/.github/actions/semantic-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
