name: Golang CI Lint

on: workflow_call
jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/konfidence-project
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup GitHub Repo Access
        uses: konfidence-project/.github/.github/actions/github-repo-access@main  

      - name: Setup Go with private repos
        uses: konfidence-project/.github/.github/actions/setup-go@main
      
      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6 