name: Golang CI Lint

on: 
  workflow_call:

jobs:
  lint:
    name: Lint Golang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Init Hermit
        uses: cashapp/activate-hermit@v1

      - name: Activate Hermit
        run: |
          eval "$(./bin/hermit env --raw)"
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Setup GitHub Repo Access
        uses: konfidence-project/.github/.github/actions/github-repo-access@v3
        with:
          private-key: ${{ secrets.KONFIDENCE_PROJECT_REPO_ACCESS_PRIVATE_KEY }}
          
      - name: Set GOPRIVATE
        run: echo "GOPRIVATE=github.com/konfidence-project" >> $GITHUB_ENV
      
      - name: Run golang linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.1.6