name: Kubebuilder Tests
on: 
  workflow_call:
    inputs:
        test-cmd:
          description: Command to run to test the kubebuilder project
          required: false
          type: string
          default: test
        before-tests:
            description: Command to run before tests (e.g., setup commands like make commands)
            required: false
            type: string
        after-tests:
            description: Command to run after tests (e.g., cleanup commands)
            required: false
            type: string

jobs:
  kubebuilder-test:
    name: Run Tests (${{ inputs.test-cmd }})
    runs-on: konfidence-large
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup GitHub Repo Access
        uses: konfidence-project/.github/.github/actions/github-repo-access@v3
        with:
          private-key: ${{secrets.KONFIDENCE_PROJECT_REPO_ACCESS_PRIVATE_KEY }}

      - name: Init Hermit
        uses: cashapp/activate-hermit@v1

      - name: Activate Hermit
        run: |
          eval "$(./bin/hermit env --raw)"
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Set GOPRIVATE
        run: echo "GOPRIVATE=github.com/konfidence-project" >> $GITHUB_ENV

      - name: Run script before tests
        if: ${{ inputs.before-tests }}
        run: ${{ inputs.before-tests }}

      - name: Run Tests
        run: |
          go mod tidy
          make ${{ inputs.test-cmd }}

      - name: Run script after tests
        if: ${{ inputs.after-tests }}
        run: ${{ inputs.after-tests }}