name: Kubebuilder Tests

on: workflow_call
jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/konfidence-project
    steps:
    - name: Clone the code
      uses: actions/checkout@v4

    - name: Clone shared actions
      uses: actions/checkout@v4
      with:
        repository: konfidence-project/.github
        path: ./.github-shared

    - name: Setup GitHub Repo Access
      uses: ./.github-shared/.github/actions/github-repo-access

    - name: Setup Go
      uses: ./.github-shared/.github/actions/setup-go

    - name: Running Tests
      run: |
        go mod tidy
        make test 