name: Kubebuilder E2E Tests
on: workflow_call
jobs:
  kubebuilder-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/konfidence-project
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup GitHub Repo Access
        uses: ./.github/actions/github-repo-access

      - name: Setup Go
        uses: ./.github/actions/setup-go

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Running Kubebuilder E2E Tests
        run: |
          go mod tidy
          make test-e2e 