name: Kubebuilder Tests
on: 
  workflow_call:
    inputs:
        test-cmd:
          description: Command to run to test the kubebuilder project
          required: false
          type: string
          default: test
        with-kind-cluster:
          description: Whether to create a Kind cluster to test against
          required: false
          type: boolean
          default: true
        install-crds:
            description: Whether to install CRDs
            required: false
            type: boolean
            default: true
        crds-version:
            description: Version of CRDs to install
            required: false
            type: string
            default: main
        before-tests:
            description: Command to run before tests (e.g., setup commands like make commands)
            required: false
            type: string
        after-tests:
            description: Command to run after tests (e.g., cleanup commands)
            required: false
            type: string

jobs:
  kubebuilder-test:
    name: Run on Ubuntu
    runs-on: konfidence-large
    steps:
      - name: Clone the code
        uses: actions/checkout@v5

      - name: Setup GitHub Repo Access
        uses: konfidence-project/.github/.github/actions/github-repo-access@v2
        with:
          private-key: ${{secrets.KONFIDENCE_PROJECT_REPO_ACCESS_PRIVATE_KEY }}
         
      - name: Setup Go
        uses: konfidence-project/.github/.github/actions/setup-go@v2

      - name: Check out CRDs Repo
        uses: actions/checkout@v5
        if: ${{ inputs.install-crds && inputs.with-kind-cluster }}
        with:
          repository: konfidence-project/crds
          ref: ${{ inputs.crds-version }}
          path: crds
          sparse-checkout: config/crd/bases # only checkout the generated CRDs
          token: ${{ env.GH_TOKEN }}

      - name: Install the latest version of kind
        if: ${{ inputs.with-kind-cluster }}
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        if: ${{ inputs.with-kind-cluster }}
        run: kind version
      
      - name: Create Kind Cluster
        if: ${{ inputs.with-kind-cluster }}
        run: |
          kind create cluster --name kind-integration-test  
          kubectl cluster-info --context kind-kind-integration-test

      - name: Install CRDs
        if: ${{ inputs.install-crds && inputs.with-kind-cluster }}
        run: |
          kubectl apply -f crds/config/crd/bases

      - name: Before Tests Setup
        if: ${{ inputs.before-tests }}
        run: ${{ inputs.before-tests }}

      - name: Run Tests
        run: |
          go mod tidy
          make ${{ inputs.test-cmd }}

      - name: After Tests Cleanup
        if: ${{ inputs.after-tests }}
        run: ${{ inputs.after-tests }}